name: Release Theme
on:
  push:
    branches: [main]
  pull_request:
    types: [closed]
    branches: [main]
    paths:
      - "**"
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get version
        id: get_version
        run: |
          VERSION=$(grep -Po "(?<=Version: ).*" style.css)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create ZIP file
        run: |
          if [ -f ".distignore" ]; then
            # Process .distignore patterns to work with zip -x
            EXCLUDE_ARGS=""
            while IFS= read -r pattern || [[ -n "$pattern" ]]; do
              # Skip empty lines and comments
              if [[ -z "$pattern" || "$pattern" =~ ^[[:space:]]*# ]]; then
                continue
              fi
              # Remove leading/trailing whitespace
              pattern=$(echo "$pattern" | xargs)
              # If pattern is a directory, add /* to exclude contents
              if [[ -d "$pattern" ]]; then
                EXCLUDE_ARGS="$EXCLUDE_ARGS \"$pattern\" \"$pattern/*\""
              else
                EXCLUDE_ARGS="$EXCLUDE_ARGS \"$pattern\""
              fi
            done < .distignore
            # Create zip with processed exclusions
            eval "zip -r morntag-hello-elementor-v${{ env.VERSION }}.zip . -x $EXCLUDE_ARGS"
          else
            zip -r morntag-hello-elementor-v${{ env.VERSION }}.zip .
          fi

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.VERSION }}
          release_name: v${{ env.VERSION }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./morntag-hello-elementor-v${{ env.VERSION }}.zip
          asset_name: morntag-hello-elementor-v${{ env.VERSION }}.zip
          asset_content_type: application/zip
